name: Azure PowerShell Automation

on:
  push:
    branches:
      - main

jobs:
  run-powershell-script:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure PowerShell module
        shell: pwsh
        run: Install-Module -Name Az -Force -AllowClobber -Scope CurrentUser

      - name: Run PowerShell script
        shell: pwsh
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: ./create-vm.ps1
